version: "3.2"
services:
    liget:
        container_name: nuget
        image: tomzo/liget:latest
        hostname: local-nuget
        volumes:
            - ./data:/data
        ports:
            - "9011:9011"
        env_file: ./.env
            

        